name: EC2 Connection Test

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            whoami
            pwd
            echo "Hello from EC2!"
            echo "Hello fabtastic world!" > lion.txt
            echo "=== System Information ==="
            uname -a
            echo -e "\n=== Distribution Info ==="
            lsb_release -a
            echo -e "\n=== CPU Info ==="
            cat /proc/cpuinfo | grep "model name" | head -n1

